version: '3'

services:
    app:
        build: .
        ports:
            - "8000:8000"
        depends_on:
            - db
        environment:
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: db
            DB_USERNAME: root
            DB_PASSWORD: secret
    db:
        image: mysql:5.7
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: db
            MYSQL_ROOT_PASSWORD: secret
